question_data = [
                                    {"category": "Vehicles", "type": "multiple", "difficulty": "hard",
                                      "question": "What was the name of the first front-wheel-drive car produced by Datsun (now Nissan)?",
                                      "correct_answer": "Cherry",
                                      "incorrect_answers": ["Sunny", "Bluebird", "Skyline"]},
                                     {"category": "Vehicles", "type": "multiple", "difficulty": "easy",
                                      "question": "The Italian automaker Lamborghini uses what animal as its logo?",
                                      "correct_answer": "Bull", "incorrect_answers": ["Bat", "Horse", "Snake"]},
                                     {"category": "Vehicles", "type": "multiple", "difficulty": "medium",
                                      "question": "Which country has the international vehicle registration letter &#039;A&#039;?",
                                      "correct_answer": "Austria",
                                      "incorrect_answers": ["Afghanistan", "Australia", "Armenia"]},
                                     {"category": "Vehicles", "type": "multiple", "difficulty": "medium",
                                      "question": "Which Japanese company is the world&#039;s largest manufacturer of motorcycles?",
                                      "correct_answer": "Honda", "incorrect_answers": ["Yamaha", "Suzuki", "Kawasaki"]},
                                     {"category": "Vehicles", "type": "multiple", "difficulty": "medium",
                                      "question": "What country is the Hussarya supercar, made by the car manufacturer &quot;Arrinera&quot;, assembled in?",
                                      "correct_answer": "Poland", "incorrect_answers": ["China", "Sweden", "Italy"]},
                                     {"category": "Vehicles", "type": "multiple", "difficulty": "easy",
                                      "question": "Which of the following car manufacturers had a war named after it?",
                                      "correct_answer": "Toyota", "incorrect_answers": ["Honda", "Ford", "Volkswagen"]},
                                     {"category": "Vehicles", "type": "multiple", "difficulty": "medium",
                                      "question": "Which of the following countries has officially banned the civilian use of dash cams in cars?",
                                      "correct_answer": "Austria",
                                      "incorrect_answers": ["United States", "Czechia", "South Korea"]},
                                     {"category": "Vehicles", "type": "multiple", "difficulty": "medium",
                                      "question": "Which of the following passenger jets is the longest?",
                                      "correct_answer": "Boeing 747-8",
                                      "incorrect_answers": ["Airbus A350-1000", "Airbus A330-200", "Boeing 787-10"]},
                                     {"category": "Vehicles", "type": "multiple", "difficulty": "hard",
                                      "question": "The difference between the lengths of a Boeing 777-300ER and an Airbus A350-1000 is closest to:",
                                      "correct_answer": "0.1m", "incorrect_answers": ["1m", "10m ", "100m"]},
                                     {"category": "Vehicles", "type": "multiple", "difficulty": "medium",
                                      "question": "Enzo Ferrari was originally an auto racer for what manufacturer before founding his own car company?",
                                      "correct_answer": "Alfa Romeo",
                                      "incorrect_answers": ["Auto Union", "Mercedes Benz", "Bentley"]},
                                     {"category": "Vehicles", "type": "multiple", "difficulty": "medium",
                                      "question": "Complete the following analogy: Audi is to Volkswagen as Infiniti is to ?",
                                      "correct_answer": "Nissan", "incorrect_answers": ["Honda", "Hyundai", "Subaru"]},
                                     {"category": "Vehicles", "type": "multiple", "difficulty": "easy",
                                      "question": "Jaguar Cars was previously owned by which car manfacturer?",
                                      "correct_answer": "Ford",
                                      "incorrect_answers": ["Chrysler", "General Motors", "Fiat"]},
                                     {"category": "Vehicles", "type": "multiple", "difficulty": "medium",
                                      "question": "Which of the following vehicles featured a full glass roof at base model?",
                                      "correct_answer": "Renault Avantime",
                                      "incorrect_answers": ["Chevy Volt", "Mercedes-Benz A-Class", "Honda Odyssey"]},
                                     {"category": "Vehicles", "type": "multiple", "difficulty": "medium",
                                      "question": "Which of the following car models has been badge-engineered (rebadged) the most?",
                                      "correct_answer": "Isuzu Trooper",
                                      "incorrect_answers": ["Holden Monaro", "Suzuki Swift", "Chevy Camaro"]},
                                     {"category": "Vehicles", "type": "boolean", "difficulty": "medium",
                                      "question": "The Chevrolet Corvette has always been made exclusively with V8 engines only.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
                                     {"category": "Vehicles", "type": "multiple", "difficulty": "easy",
                                      "question": "Which of the following collision avoidance systems helps airplanes avoid colliding with each other?",
                                      "correct_answer": "TCAS", "incorrect_answers": ["GPWS", "OCAS", "TAWS"]},
                                     {"category": "Vehicles", "type": "multiple", "difficulty": "hard",
                                      "question": "Which of these is NOT a car model produced by Malaysian car manufacturer Proton?",
                                      "correct_answer": "Kelisa", "incorrect_answers": ["Saga", "Perdana", "Inspira"]},
                                     {"category": "Vehicles", "type": "multiple", "difficulty": "easy",
                                      "question": "Which of these companies does NOT manufacture motorcycles?",
                                      "correct_answer": "Toyota", "incorrect_answers": ["Honda", "Kawasaki", "Yamaha"]},
                                     {"category": "Vehicles", "type": "boolean", "difficulty": "easy",
                                      "question": "The full English name of the car manufacturer BMW is Bavarian Motor Works",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "Vehicles", "type": "multiple", "difficulty": "hard",
                                      "question": "Which one of these chassis codes are used by BMW 3-series?",
                                      "correct_answer": "E46", "incorrect_answers": ["E39", "E85", "F10"]},
                                     {"category": "Vehicles", "type": "multiple", "difficulty": "medium",
                                      "question": "Which supercar company is from Sweden?",
                                      "correct_answer": "Koenigsegg",
                                      "incorrect_answers": ["Bugatti", "Lamborghini", "McLaren"]},
                                     {"category": "Vehicles", "type": "multiple", "difficulty": "medium",
                                      "question": "Which car brand does NOT belong to General Motors?",
                                      "correct_answer": "Ford",
                                      "incorrect_answers": ["Buick", "Cadillac", "Chevrolet"]},
                                     {"category": "Vehicles", "type": "multiple", "difficulty": "easy",
                                      "question": "Automobiles produced by Telsa Motors operate on which form of energy?",
                                      "correct_answer": "Electricity",
                                      "incorrect_answers": ["Gasoline", "Diesel", "Nuclear"]},
                                     {"category": "Vehicles", "type": "multiple", "difficulty": "hard",
                                      "question": "Which car is the first mass-produced hybrid vehicle?",
                                      "correct_answer": "Toyota Prius",
                                      "incorrect_answers": ["Chevrolet Volt", "Honda Fit", "Peugeot 308 R HYbrid"]},
                                     {"category": "Vehicles", "type": "multiple", "difficulty": "medium",
                                      "question": "Which of these car models are produced by Lamborghini?",
                                      "correct_answer": "Aventador", "incorrect_answers": ["Huayra", "918", "Chiron"]},
                                     {"category": "Vehicles", "type": "multiple", "difficulty": "hard",
                                      "question": "Which Variable Valve Timing technology is used by BMW?",
                                      "correct_answer": "VANOS", "incorrect_answers": ["VVT-iw", "VVEL", "MultiAir"]},
                                     {"category": "Vehicles", "type": "boolean", "difficulty": "medium",
                                      "question": "When BMW was established in 1916, it was producing automobiles.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
                                     {"category": "Vehicles", "type": "multiple", "difficulty": "medium",
                                      "question": "What do the 4 Rings in Audi&#039;s Logo represent?",
                                      "correct_answer": "Previously independent automobile manufacturers",
                                      "incorrect_answers": ["States in which Audi makes the most sales",
                                                            "Main cities vital to Audi",
                                                            "Countries in which Audi makes the most sales"]},
                                     {"category": "Vehicles", "type": "multiple", "difficulty": "hard",
                                      "question": "How much horsepower is produced by the SD40-2 Locomotive?",
                                      "correct_answer": "3,000", "incorrect_answers": ["3,200", "2,578", "2,190"]},
                                     {"category": "Vehicles", "type": "multiple", "difficulty": "hard",
                                      "question": "What engine is in the Lexus SC400?", "correct_answer": "1UZ-FE",
                                      "incorrect_answers": ["2JZ-GTE", "7M-GTE", "5M-GE"]},
                                     {"category": "Vehicles", "type": "multiple", "difficulty": "hard",
                                      "question": "Volkswagen&#039;s legendary VR6 engine has cylinders positioned at what degree angle?",
                                      "correct_answer": "15 Degree",
                                      "incorrect_answers": ["30 Degree", "45 Degree", "90 Degree"]},
                                     {"category": "Vehicles", "type": "boolean", "difficulty": "medium",
                                      "question": "Arriva is owned by the Deutsche Bahn.", "correct_answer": "True",
                                      "incorrect_answers": ["False"]},
                                     {"category": "Vehicles", "type": "boolean", "difficulty": "medium",
                                      "question": "The General Motors EV1 was the first street-legal production electric vehicle.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
                                     {"category": "Vehicles", "type": "boolean", "difficulty": "medium",
                                      "question": "Bugatti was an Italian car manufacturer.", "correct_answer": "False",
                                      "incorrect_answers": ["True"]},
                                     {"category": "Vehicles", "type": "multiple", "difficulty": "easy",
                                      "question": "Which car tire manufacturer is famous for its &quot;P Zero&quot; line?",
                                      "correct_answer": "Pirelli",
                                      "incorrect_answers": ["Goodyear", "Bridgestone", "Michelin"]},
                                     {"category": "Vehicles", "type": "multiple", "difficulty": "medium",
                                      "question": "When was Cadillac founded?", "correct_answer": "1902",
                                      "incorrect_answers": ["1964", "1898", "1985"]},
                                     {"category": "Vehicles", "type": "multiple", "difficulty": "medium",
                                      "question": "Which one of the following is not made by Ford?",
                                      "correct_answer": "Camry", "incorrect_answers": ["Fusion", "Model A", "F-150"]},
                                     {"category": "Vehicles", "type": "multiple", "difficulty": "easy",
                                      "question": "The LS1 engine is how many cubic inches?", "correct_answer": "346",
                                      "incorrect_answers": ["350", "355", "360"]},
                                     {"category": "Vehicles", "type": "multiple", "difficulty": "easy",
                                      "question": "The LS2 engine is how many cubic inches?", "correct_answer": "364",
                                      "incorrect_answers": ["346", "376", "402"]},
                                     {"category": "Vehicles", "type": "multiple", "difficulty": "easy",
                                      "question": "The LS7 engine is how many cubic inches?", "correct_answer": "427",
                                      "incorrect_answers": ["346", "364", "376"]},
                                     {"category": "Vehicles", "type": "multiple", "difficulty": "easy",
                                      "question": "The LS3 engine is how many cubic inches?", "correct_answer": "376",
                                      "incorrect_answers": ["346", "364", "427"]},
                                     {"category": "Vehicles", "type": "multiple", "difficulty": "medium",
                                      "question": "Which car manufacturer created the &quot;Aventador&quot;?",
                                      "correct_answer": "Lamborghini",
                                      "incorrect_answers": ["Ferrari", "Pagani", "Bugatti"]},
                                     {"category": "Vehicles", "type": "multiple", "difficulty": "hard",
                                      "question": "Which Audi does not use Haldex based all wheel drive system?",
                                      "correct_answer": "Audi A8",
                                      "incorrect_answers": ["Audi TT", "Audi S3", "Audi A3"]},
                                     {"category": "Vehicles", "type": "multiple", "difficulty": "hard",
                                      "question": "What year did the Chevrolet LUV mini truck make its debut?",
                                      "correct_answer": "1972", "incorrect_answers": ["1982", "1975", "1973"]},
                                     {"category": "Vehicles", "type": "multiple", "difficulty": "hard",
                                      "question": "What kind of train was Stepney, a train on the Bluebell Railway notable for his appearance in &quot;The Railway Series&quot;?",
                                      "correct_answer": "LB&amp;SCR A1X",
                                      "incorrect_answers": ["LB&amp;SCR E2", "LB&amp;SCR J1", "LB&amp;SCR D1"]},
                                     {"category": "Vehicles", "type": "boolean", "difficulty": "medium",
                                      "question": "The majority of Subaru vehicles are made in China.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
                                     {"category": "Vehicles", "type": "multiple", "difficulty": "hard",
                                      "question": "What car manufacturer gave away their patent for the seat-belt in the interest of saving lives?",
                                      "correct_answer": "Volvo", "incorrect_answers": ["Ferrari", "Ford", "Renault"]},
                                     {"category": "Vehicles", "type": "boolean", "difficulty": "medium",
                                      "question": "The snowmobile was invented by Canadian Joseph-Armand Bombardier in 1937.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "Vehicles", "type": "multiple", "difficulty": "easy",
                                      "question": "What country was the Trabant 601 manufactured in?",
                                      "correct_answer": "East Germany",
                                      "incorrect_answers": ["Soviet Union", "Hungary", "France"]},
                                     {"category": "Vehicles", "type": "multiple", "difficulty": "medium",
                                      "question": "Which of these cars is NOT considered one of the 5 Modern Supercars by Ferrari?",
                                      "correct_answer": "Testarossa",
                                      "incorrect_answers": ["Enzo Ferrari", "F40", "288 GTO"]}
]
